sonar.organization=1bt-wiki
sonar.projectKey=1bt-project-wiki
sonar.projectName=Monorepo-deploy-demo

sonar.sources=apps/api/src,apps/web/src,packages/db/src,packages/ui/src
sonar.tests=apps/api/src,apps/web/cypress
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,apps/web/cypress/**
sonar.exclusions=**/node_modules/**,**/.next/**,**/.turbo/**,**/dist/**,**/build/**,**/coverage/**,**/.scannerwork/**,**/*.d.ts

sonar.sourceEncoding=UTF-8
