name: API CI

on:
  pull_request:
    branches:
      - main
      - dev

  push:
      branches:
        - dev
      paths:
        - 'apps/api/**'
        - 'packages/db/**'
        - '.github/workflows/deploy-api.yaml'

jobs:
  api-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm --filter @repo/db build

      - name: Lint API
        run: pnpm --filter api lint

      - name: Run API Tests
        run: pnpm --filter api test

      - name: Build API
        run: pnpm --filter api build