name: API CI

on:
  pull_request:
    paths:
      - 'apps/api/**'
  push:
      branches:
        - dev
        - main
      paths:
        - 'apps/api/**'

jobs:
  api-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build DB Package
        run: pnpm --filter db build

      - name: Lint API
        run: pnpm --filter api lint

      - name: Run API Tests
        run: pnpm --filter api test

      - name: Build API
        run: pnpm --filter api build